import 'package:flutter/material.dart';

// void main() {
//   runApp(const FigmaToCodeApp());
// }

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
// ignore: camel_case_types
class add_accountt extends StatelessWidget {
  const add_accountt({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        // ignore: prefer_const_literals_to_create_immutables
        body: ListView(children: [
          const Rectangle14(),
        ]),
      ),
    );
  }
}

class Rectangle14 extends StatelessWidget {
  const Rectangle14({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 116,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(26),
            ),
          ),
        ),
        const SizedBox(
          width: 139,
          height: 28,
          child: Text(
            'ADD ACCOUNT ',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Colors.black,
              fontSize: 16,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 46,
          height: 28,
          child: Text(
            'Profile',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 28,
          decoration: const ShapeDecoration(
            shape: RoundedRectangleBorder(
              side: BorderSide(
                width: 6,
                strokeAlign: BorderSide.strokeAlignCenter,
              ),
            ),
          ),
        ),
        Container(
          width: 36,
          height: 31,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/36x31"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 29,
          height: 16,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/29x16"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 25,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/25x21"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 27,
          height: 28,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/27x28"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 29,
          height: 42,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/29x42"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 347,
          height: 54,
          decoration: ShapeDecoration(
            color: const Color(0xCCD9D9D9),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        Container(
          width: 29,
          height: 42,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/29x42"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        const Text(
          'Search Bank',
          style: TextStyle(
            color: Colors.black,
            fontSize: 18,
            fontFamily: 'Inter',
            fontWeight: FontWeight.w300,
            height: 0,
          ),
        ),
        Container(
          width: 41,
          height: 30,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/41x30"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        const SizedBox(
          width: 80,
          height: 28,
          child: Text(
            'All Banks',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Colors.black,
              fontSize: 16,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 98,
          height: 28,
          child: Text(
            'Allahabad Bank',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Color(0x91011500),
              fontSize: 13,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w300,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 80,
          height: 28,
          child: Text(
            'Andhra Bank',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Color(0x91011500),
              fontSize: 13,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w300,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 123,
          height: 28,
          child: Text(
            'Apna Sahakari bank',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Color(0x91011500),
              fontSize: 13,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w300,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 63,
          height: 28,
          child: Text(
            'Axis Bank ',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Color(0x91011500),
              fontSize: 13,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w300,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 129,
          height: 28,
          child: Text(
            'Punjab National Bank',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Color(0x91011500),
              fontSize: 13,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w300,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 93,
          height: 28,
          child: Text(
            'Bank of Baroda',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Color(0x91011500),
              fontSize: 13,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w300,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 73,
          height: 28,
          child: Text(
            'HDFC Bank',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Color(0x91011500),
              fontSize: 13,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w300,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 63,
          height: 28,
          child: Text(
            'ICICI Bank',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Color(0x91011500),
              fontSize: 13,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w300,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 121,
          height: 28,
          child: Text(
            'State Bank of India',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Color(0x91011500),
              fontSize: 13,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w300,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 132,
          height: 28,
          child: Text(
            'Punjab National Bank',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Color(0x91011500),
              fontSize: 13,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w300,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 19,
          height: 13,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/19x13"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 19,
          height: 13,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/19x13"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 19,
          height: 13,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/19x13"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 19,
          height: 13,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/19x13"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 19,
          height: 13,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/19x13"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 19,
          height: 13,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/19x13"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 19,
          height: 13,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/19x13"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 19,
          height: 13,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/19x13"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 19,
          height: 13,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/19x13"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 19,
          height: 13,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/19x13"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 19,
          height: 13,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/19x13"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 189,
          height: 30,
          decoration: ShapeDecoration(
            color: const Color(0xFF011400),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
          ),
        ),
      ],
    );
  }
}
