import 'package:flutter/material.dart';

// void main() {
//   runApp(const FigmaToCodeApp());
// }

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: const [
          Ellipse1(),
        ]),
      ),
    );
  }
}

class Ellipse1 extends StatelessWidget {
  const Ellipse1({super.key});

  @override
  Widget build(BuildContext context) {
    const sizedBox = SizedBox(
      width: 211,
      height: 28,
      child: Text(
        'INRXXXX.XX',
        style: TextStyle(
          color: Color(0xFFFCF1F1),
          fontSize: 32,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w800,
          height: 0,
        ),
      ),
    );
    return Column(
      children: [
        Container(
          width: 60,
          height: 63,
          decoration: const ShapeDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/60x63"),
              fit: BoxFit.fill,
            ),
            shape: OvalBorder(side: BorderSide(width: 1)),
            shadows: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 4,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
        ),
        const SizedBox(
          width: 104,
          child: Text(
            'WELCOME',
            style: TextStyle(
              color: Colors.black,
              fontSize: 16,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 347,
          height: 188,
          decoration: ShapeDecoration(
            gradient: const LinearGradient(
              begin: Alignment(0.00, -1.00),
              end: Alignment(0, 1),
              colors: [Color(0xFFF4A023), Color(0xFFF4A023), Color(0x540C0B0B)],
            ),
            shape: RoundedRectangleBorder(
              side: BorderSide(
                width: 1,
                color: Colors.black.withOpacity(0.20000000298023224),
              ),
              borderRadius: BorderRadius.circular(22),
            ),
          ),
        ),
        const SizedBox(
          width: 81,
          height: 28,
          child: Text(
            'Balance',
            style: TextStyle(
              color: Color(0xFFFCF1F1),
              fontSize: 16,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        sizedBox,
        Container(
          width: 60,
          height: 46,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/60x46"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'Recent Transaction ',
            style: TextStyle(
              color: Colors.black,
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 70,
          height: 28,
          child: Text(
            'View All',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 73,
          height: 28,
          child: Text(
            'History',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Colors.black,
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 54,
          height: 52,
          decoration: ShapeDecoration(
            color: const Color(0x66000200),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'John',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 92,
          height: 28,
          child: Text(
            '01-Jan-2024',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 74,
          height: 28,
          child: Text(
            '-INR40.00',
            style: TextStyle(
              color: Color(0xFFF80B0B),
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 40,
          height: 28,
          child: Text(
            'Sent',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Rai',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 86,
          height: 28,
          child: Text(
            '+INR200.00',
            style: TextStyle(
              color: Color(0xFF0BBE48),
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 92,
          height: 28,
          child: Text(
            '04-Jan-2024',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Receive ',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 54,
          height: 52,
          decoration: ShapeDecoration(
            color: const Color(0x66000200),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Tony',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 74,
          height: 28,
          child: Text(
            '+INR10.00',
            style: TextStyle(
              color: Color(0xFF1BB73E),
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 92,
          height: 28,
          child: Text(
            '10-Jan-2024',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 54,
          height: 52,
          decoration: ShapeDecoration(
            color: const Color(0x66000200),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Jai',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 81,
          height: 28,
          child: Text(
            '-INR100.00',
            style: TextStyle(
              color: Color(0xFFFF1B37),
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 92,
          height: 28,
          child: Text(
            '12-Jan-2024',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 40,
          height: 28,
          child: Text(
            'Sent',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 54,
          height: 52,
          decoration: ShapeDecoration(
            color: const Color(0x66000200),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Receive ',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 36,
          height: 31,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/36x31"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Home',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 29,
          height: 16,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/29x16"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 25,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/25x21"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 27,
          height: 28,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/27x28"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 430,
          height: 116,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(26),
            ),
          ),
        ),
        Container(
          width: 28,
          decoration: const ShapeDecoration(
            shape: RoundedRectangleBorder(
              side: BorderSide(
                width: 6,
                strokeAlign: BorderSide.strokeAlignCenter,
              ),
            ),
          ),
        ),
        const SizedBox(
          width: 81,
          height: 28,
          child: Text(
            'NodePay',
            style: TextStyle(
              color: Color(0xFFFCF1F1),
              fontSize: 16,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 27,
          height: 31,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/27x31"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 29,
          height: 30,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/29x30"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 27,
          height: 31,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/27x31"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 29,
          height: 30,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/29x30"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 430,
          height: 515,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(30),
            ),
          ),
        ),
        Container(
          width: 377,
          height: 220,
          decoration: ShapeDecoration(
            gradient: const RadialGradient(
              center: Alignment(0, 1),
              radius: 0,
              colors: [Color(0xFFECA315), Color(0x00D9D9D9)],
            ),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        Container(
          width: 40,
          height: 31,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/40x31"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        const SizedBox(
          width: 54,
          height: 28,
          child: Text(
            'Refresh here',
            style: TextStyle(
              color: Colors.white,
              fontSize: 8,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 31,
          height: 33,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/31x33"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 189,
          height: 30,
          decoration: ShapeDecoration(
            color: const Color(0xFF011400),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
          ),
        ),
      ],
    );
  }
}
