import 'package:flutter/material.dart';

// void main() {
//   runApp(const FigmaToCodeApp());
// }

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Manu extends StatelessWidget {
  const Manu({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 255, 255, 255),
      ),
      home: Scaffold(
        body: ListView(children: const [
          Rectangle14(),
        ]),
      ),
    );
  }
}

class Rectangle14 extends StatelessWidget {
  const Rectangle14({super.key});

  @override
  Widget build(BuildContext context) {
    const sizedBox = SizedBox(
      width: 195,
      height: 28,
      child: Text(
        'Account Information',
        style: TextStyle(
          color: Colors.black,
          fontSize: 18,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w800,
          height: 0,
        ),
      ),
    );
    return Column(
      children: [
        Container(
          width: 430,
          height: 116,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(26),
            ),
          ),
        ),
        const SizedBox(
          width: 139,
          height: 28,
          child: Text(
            'ACCOUNT ',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Colors.black,
              fontSize: 16,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 46,
          height: 28,
          child: Text(
            'Profile',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 28,
          decoration: const ShapeDecoration(
            shape: RoundedRectangleBorder(
              side: BorderSide(
                width: 6,
                strokeAlign: BorderSide.strokeAlignCenter,
              ),
            ),
          ),
        ),
        Container(
          width: 36,
          height: 31,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/36x31"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 29,
          height: 16,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/29x16"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 25,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/25x21"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 27,
          height: 28,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/27x28"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'General',
            style: TextStyle(
              color: Color(0x68000200),
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'Account Information',
            style: TextStyle(
              color: Colors.black,
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'Setup Account Pin',
            style: TextStyle(
              color: Color(0xFF000400),
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'Order Debit Card ',
            style: TextStyle(
              color: Color(0xFF011400),
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'Change Account Pin',
            style: TextStyle(
              color: Color(0xFF000400),
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'Add Bank Account',
            style: TextStyle(
              color: Color(0xFF000400),
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'General',
            style: TextStyle(
              color: Color(0x68000200),
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'Notification',
            style: TextStyle(
              color: Colors.black,
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'Logout',
            style: TextStyle(
              color: Colors.black,
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 206,
          height: 28,
          child: Text(
            'Fingerprint/Face Login',
            style: TextStyle(
              color: Colors.black,
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 30,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/30x21"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 30,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/30x21"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 30,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/30x21"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 30,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/30x21"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 30,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/30x21"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 41,
          height: 30,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/41x30"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 32,
          height: 31,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/32x31"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 40,
          height: 27,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/40x27"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 27,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/27x21"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 31,
          height: 25,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/31x25"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 30,
          height: 26,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/30x26"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 26,
          height: 31,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/26x31"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 27,
          height: 27,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/27x27"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 34,
          height: 23,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/34x23"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 23,
          height: 26,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/23x26"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 30,
          height: 28,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/30x28"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 29,
          height: 42,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/29x42"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 430,
          height: 95,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(26),
            ),
          ),
        ),
        const SizedBox(
          width: 139,
          height: 28,
          child: Text(
            'ACCOUNT ',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Colors.black,
              fontSize: 16,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 46,
          height: 28,
          child: Text(
            'Profile',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 28,
          decoration: const ShapeDecoration(
            shape: RoundedRectangleBorder(
              side: BorderSide(
                width: 6,
                strokeAlign: BorderSide.strokeAlignCenter,
              ),
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'General',
            style: TextStyle(
              color: Color(0x68000200),
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'General',
            style: TextStyle(
              color: Color(0x68000200),
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        sizedBox,
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'Notification',
            style: TextStyle(
              color: Colors.black,
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 206,
          height: 28,
          child: Text(
            'Fingerprint/Face Login',
            style: TextStyle(
              color: Colors.black,
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'Logout',
            style: TextStyle(
              color: Colors.black,
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'Setup Account Pin',
            style: TextStyle(
              color: Color(0xFF000400),
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'Change Account Pin',
            style: TextStyle(
              color: Color(0xFF000400),
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'Add Bank Account',
            style: TextStyle(
              color: Color(0xFF000400),
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'Order Debit Card ',
            style: TextStyle(
              color: Color(0xFF011400),
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 30,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/30x21"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 30,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/30x21"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 30,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/30x21"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 30,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/30x21"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 30,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/30x21"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 41,
          height: 30,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/41x30"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 32,
          height: 31,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/32x31"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 27,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/27x21"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 31,
          height: 25,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/31x25"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 30,
          height: 26,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/30x26"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 26,
          height: 31,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/26x31"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 27,
          height: 27,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/27x27"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 23,
          height: 26,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/23x26"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 30,
          height: 28,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/30x28"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 29,
          height: 42,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/29x42"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 36,
          height: 31,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/36x31"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 29,
          height: 16,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/29x16"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 25,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/25x21"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 27,
          height: 28,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/27x28"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 40,
          height: 27,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/40x27"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 34,
          height: 23,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/34x23"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 189,
          height: 30,
          decoration: ShapeDecoration(
            color: const Color(0xFF011400),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
          ),
        ),
      ],
    );
  }
}

// import 'package:flutter/material.dart';

// class Manu extends StatelessWidget {
//   const Manu({Key? key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       theme: ThemeData.dark().copyWith(
//         scaffoldBackgroundColor: const Color.fromARGB(255, 255, 255, 255),
//       ),
//       home: Scaffold(
//         body: ListView(
//           children: const [
//             Rectangle14(),
//           ],
//         ),
//       ),
//     );
//   }
// }

// class Rectangle14 extends StatelessWidget {
//   const Rectangle14({Key? key});

//   @override
//   Widget build(BuildContext context) {
//     return Column(
//       children: [
//         Container(
//           width: 430,
//           height: 116,
//           decoration: BoxDecoration(
//             color: Colors.white,
//             borderRadius: BorderRadius.circular(26),
//           ),
//           // Add your content for the first container here
//         ),
//         SizedBox(
//           width: 139,
//           height: 28,
//           child: Text(
//             'ACCOUNT ',
//             textAlign: TextAlign.center,
//             style: TextStyle(
//               color: Colors.black,
//               fontSize: 16,
//               fontFamily: 'Inter',
//               fontWeight: FontWeight.w800,
//             ),
//           ),
//         ),
//         SizedBox(
//           width: 46,
//           height: 28,
//           child: Text(
//             'Profile',
//             style: TextStyle(
//               color: Colors.black,
//               fontSize: 14,
//               fontFamily: 'Inter',
//               fontWeight: FontWeight.w800,
//             ),
//           ),
//         ),
//         // Add more containers and texts here as needed
//       ],
//     );
//   }
// }

// // void main() {
// //   runApp(const Manu());
// // }

