import 'package:flutter/material.dart';

// void main() {
//   runApp(const FigmaToCodeApp());
// }

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: const [
          Rectangle14(),
        ]),
      ),
    );
  }
}

class Rectangle14 extends StatelessWidget {
  const Rectangle14({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 116,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(26),
            ),
          ),
        ),
        const SizedBox(
          width: 139,
          height: 28,
          child: Text(
            'TRANSACTION',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Colors.black,
              fontSize: 16,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 195,
          height: 28,
          child: Text(
            'Recent Transaction ',
            style: TextStyle(
              color: Colors.black,
              fontSize: 18,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'John',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 76,
          height: 28,
          child: Text(
            '-INR40.00',
            style: TextStyle(
              color: Color(0xFFE51515),
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 92,
          height: 28,
          child: Text(
            '01-Jan-2024',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 40,
          height: 28,
          child: Text(
            'Sent',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 70,
          height: 28,
          child: Text(
            'View All',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 54,
          height: 52,
          decoration: ShapeDecoration(
            color: const Color(0x660C0B0B),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Jai',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 88,
          height: 28,
          child: Text(
            'Transaction',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 92,
          height: 28,
          child: Text(
            '12-Jan-2024',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 40,
          height: 28,
          child: Text(
            'Sent',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 54,
          height: 52,
          decoration: ShapeDecoration(
            color: const Color(0x66000200),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Tony',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 92,
          height: 28,
          child: Text(
            '10-Jan-2024',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 54,
          height: 52,
          decoration: ShapeDecoration(
            color: const Color(0x66000200),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Rai',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 86,
          height: 28,
          child: Text(
            '+INR200.00',
            style: TextStyle(
              color: Color(0xFF10B721),
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 92,
          height: 28,
          child: Text(
            '04-Jan-2024',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Receive ',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Receive ',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 54,
          height: 52,
          decoration: ShapeDecoration(
            color: const Color(0x66000200),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        Container(
          width: 28,
          decoration: const ShapeDecoration(
            shape: RoundedRectangleBorder(
              side: BorderSide(
                width: 6,
                strokeAlign: BorderSide.strokeAlignCenter,
              ),
            ),
          ),
        ),
        Container(
          width: 36,
          height: 31,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/36x31"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 29,
          height: 16,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/29x16"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 25,
          height: 21,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/25x21"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 27,
          height: 28,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/27x28"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 74,
          height: 45,
          decoration: ShapeDecoration(
            color: const Color(0xFF000200),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        Container(
          width: 74,
          height: 45,
          decoration: ShapeDecoration(
            color: const Color(0x68000200),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        Container(
          width: 74,
          height: 45,
          decoration: ShapeDecoration(
            color: const Color(0x68000200),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        Container(
          width: 74,
          height: 45,
          decoration: ShapeDecoration(
            color: const Color(0x68000200),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        const Text(
          'D',
          textAlign: TextAlign.center,
          style: TextStyle(
            color: Colors.white,
            fontSize: 18,
            fontFamily: 'Inter',
            fontWeight: FontWeight.w900,
            height: 0,
          ),
        ),
        const Text(
          'W',
          textAlign: TextAlign.center,
          style: TextStyle(
            color: Color(0xFF011500),
            fontSize: 18,
            fontFamily: 'Inter',
            fontWeight: FontWeight.w900,
            height: 0,
          ),
        ),
        const Text(
          'M',
          textAlign: TextAlign.center,
          style: TextStyle(
            color: Colors.black,
            fontSize: 18,
            fontFamily: 'Inter',
            fontWeight: FontWeight.w900,
            height: 0,
          ),
        ),
        const Text(
          'Y',
          textAlign: TextAlign.center,
          style: TextStyle(
            color: Colors.black,
            fontSize: 18,
            fontFamily: 'Inter',
            fontWeight: FontWeight.w900,
            height: 0,
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Kritika',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 92,
          height: 28,
          child: Text(
            '12-Jan-2024',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 40,
          height: 28,
          child: Text(
            'Sent',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 54,
          height: 52,
          decoration: ShapeDecoration(
            color: const Color(0x66000200),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Tina',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 92,
          height: 28,
          child: Text(
            '10-Jan-2024',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 54,
          height: 52,
          decoration: ShapeDecoration(
            color: const Color(0x66000200),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Ram',
            style: TextStyle(
              color: Colors.black,
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 92,
          height: 28,
          child: Text(
            '04-Jan-2024',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Receive ',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Receive ',
            style: TextStyle(
              color: Colors.black,
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 54,
          height: 52,
          decoration: ShapeDecoration(
            color: const Color(0x66000200),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        SizedBox(
          width: 58,
          height: 28,
          child: Text(
            'Heena',
            style: TextStyle(
              color: Colors.black.withOpacity(0.25),
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        SizedBox(
          width: 92,
          height: 28,
          child: Text(
            '12-Jan-2024',
            style: TextStyle(
              color: Colors.black.withOpacity(0.25),
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        SizedBox(
          width: 40,
          height: 28,
          child: Text(
            'Sent',
            style: TextStyle(
              color: Colors.black.withOpacity(0.25),
              fontSize: 12,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w400,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 54,
          height: 52,
          decoration: ShapeDecoration(
            gradient: const LinearGradient(
              begin: Alignment(0.00, -1.00),
              end: Alignment(0, 1),
              colors: [Color(0xFF000200), Color(0x00000200)],
            ),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        Container(
          width: 367,
          height: 65,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        Container(
          width: 367,
          height: 65,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        Container(
          width: 367,
          height: 65,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        Container(
          width: 367,
          height: 65,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        Container(
          width: 367,
          height: 65,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        Container(
          width: 367,
          height: 65,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        Container(
          width: 367,
          height: 65,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        Container(
          width: 367,
          height: 65,
          decoration: ShapeDecoration(
            gradient: const LinearGradient(
              begin: Alignment(0.00, -1.00),
              end: Alignment(0, 1),
              colors: [Colors.white, Colors.white],
            ),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        const SizedBox(
          width: 86,
          height: 28,
          child: Text(
            '+INR200.00',
            style: TextStyle(
              color: Color(0xFF10B721),
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 86,
          height: 28,
          child: Text(
            '+INR200.00',
            style: TextStyle(
              color: Color(0xFF10B721),
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 86,
          height: 28,
          child: Text(
            '+INR200.00',
            style: TextStyle(
              color: Color(0xFF10B721),
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 76,
          height: 28,
          child: Text(
            '-INR40.00',
            style: TextStyle(
              color: Color(0xFFE51515),
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 76,
          height: 28,
          child: Text(
            '-INR40.00',
            style: TextStyle(
              color: Color(0xFFE51515),
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        const SizedBox(
          width: 76,
          height: 28,
          child: Text(
            '-INR40.00',
            style: TextStyle(
              color: Color(0x3FE51515),
              fontSize: 14,
              fontFamily: 'Inter',
              fontWeight: FontWeight.w800,
              height: 0,
            ),
          ),
        ),
        Container(
          width: 27,
          height: 31,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/27x31"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 29,
          height: 30,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/29x30"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 29,
          height: 30,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/29x30"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 27,
          height: 31,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/27x31"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 29,
          height: 30,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/29x30"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 29,
          height: 30,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/29x30"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 27,
          height: 31,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/27x31"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 27,
          height: 31,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/27x31"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 367,
          height: 65,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        Container(
          width: 29,
          height: 42,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/29x42"),
              fit: BoxFit.contain,
            ),
          ),
        ),
        Container(
          width: 189,
          height: 30,
          decoration: ShapeDecoration(
            color: const Color(0xFF011400),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
          ),
        ),
      ],
    );
  }
}
